services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: gateway_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - server
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

  server:
    build: ./server
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      PUBLIC_HOST: ${PUBLIC_HOST}
      PUBLIC_PORT: ${PUBLIC_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CREATOR_EMAIL: ${CREATOR_EMAIL}

      # OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_TOKEN_URL: ${GOOGLE_TOKEN_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_TOKEN_URL: ${GITHUB_TOKEN_URL}
      GITHUB_USER_DETAILS_URL: ${GITHUB_USER_DETAILS_URL}
      GITHUB_USER_EMAIL_URL: ${GITHUB_USER_EMAIL_URL}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
      REFRESH_TOKEN_EXPIRATION_DAYS: ${REFRESH_TOKEN_EXPIRATION_DAYS}

      # MinIO
      MINIO_END_POINT: minio
      MINIO_PORT: ${MINIO_PORT}
      MINIO_SSL: ${MINIO_SSL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_AVATARS_BUCKET: ${MINIO_AVATARS_BUCKET}
      MINIO_MARKDOWN_IMG_BUCKET: ${MINIO_MARKDOWN_IMG_BUCKET}

      AUTH_REDIRECT_URI: ${AUTH_REDIRECT_URI}
    depends_on:
      - db
      - minio
    restart: always

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_ENVIRONMENT: ${VITE_ENVIRONMENT}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_REDIRECT_URI: ${VITE_GOOGLE_REDIRECT_URI}
        VITE_GITHUB_CLIENT_ID: ${VITE_GITHUB_CLIENT_ID}
        VITE_GITHUB_REDIRECT_URI: ${VITE_GITHUB_REDIRECT_URI}
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: always
    command: --config /etc/vector/vector.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector/vector.toml:/etc/vector/vector.toml:ro

  loki:
    image: grafana/loki:3.5.8
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
      - loki_compactor:/loki/compactor
    restart: always

  grafana:
    image: grafana/grafana:12.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    restart: always

volumes:
  pgdata:
  minio_data:
  grafana_data:
  loki_data:
  loki_compactor:
